-- 100 INSERT records for procedures table in Oracle syntax
-- Generated for dental clinic database

INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (1, 1, 11, DATE '2024-01-15', 'Initial examination completed. Minor cavity detected on upper left molar.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (2, 3, 21, DATE '2024-01-16', 'Root canal procedure initiated. Patient tolerated procedure well.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (3, 2, 32, DATE '2024-01-17', 'Routine cleaning performed. Slight plaque buildup removed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (4, 4, 14, DATE '2024-01-18', 'Crown preparation completed. Temporary crown placed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (5, 1, 25, DATE '2024-01-19', 'Comprehensive oral examination. Recommend fluoride treatment.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (6, 5, NULL, DATE '2024-01-20', 'Orthodontic consultation. Treatment plan discussed with patient.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (7, 2, 18, DATE '2024-01-21', 'Deep cleaning performed on lower right quadrant.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (8, 6, 12, DATE '2024-01-22', 'Tooth extraction completed. Post-operative care instructions given.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (9, 3, 31, DATE '2024-01-23', 'Second session of root canal treatment. Canal cleaning progressing well.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (10, 7, 16, DATE '2024-01-24', 'Dental filling completed. Composite material used.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (11, 1, 22, DATE '2024-01-25', 'Routine checkup. No significant issues found.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (12, 8, NULL, DATE '2024-01-26', 'Teeth whitening session completed. Good results achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (13, 4, 28, DATE '2024-01-27', 'Final crown fitting. Perfect occlusion achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (14, 2, 45, DATE '2024-01-28', 'Periodontal scaling completed. Gum health improving.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (15, 9, 17, DATE '2024-01-29', 'Dental implant placement surgery. Procedure successful.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (16, 1, 33, DATE '2024-01-30', 'Follow-up examination. Healing progressing normally.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (17, 5, NULL, DATE '2024-01-31', 'Orthodontic adjustment. Brackets tightened appropriately.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (18, 7, 24, DATE '2024-02-01', 'Large composite filling placed. Patient experienced minimal discomfort.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (19, 3, 13, DATE '2024-02-02', 'Root canal completion. Canal sealed successfully.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (20, 10, 26, DATE '2024-02-03', 'Bridge preparation initiated. Abutment teeth prepared.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (21, 2, 41, DATE '2024-02-04', 'Professional cleaning with fluoride application.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (22, 6, 35, DATE '2024-02-05', 'Surgical extraction of impacted wisdom tooth. Recovery instructions provided.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (23, 1, 19, DATE '2024-02-06', 'Annual checkup completed. Recommend regular flossing.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (24, 4, 27, DATE '2024-02-07', 'Porcelain crown cemented. Excellent fit and appearance.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (25, 8, NULL, DATE '2024-02-08', 'Second whitening session. Significant color improvement noted.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (26, 7, 15, DATE '2024-02-09', 'Small cavity filled with amalgam. No complications.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (27, 9, 38, DATE '2024-02-10', 'Implant healing assessment. Osseointegration progressing well.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (28, 2, 29, DATE '2024-02-11', 'Gum disease treatment. Antibiotic therapy initiated.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (29, 5, NULL, DATE '2024-02-12', 'Orthodontic progress evaluation. Teeth movement on track.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (30, 3, 23, DATE '2024-02-13', 'Endodontic retreatment completed. Previous work revised.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (31, 1, 34, DATE '2024-02-14', 'Preventive examination. Early caries detected and treated.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (32, 11, 42, DATE '2024-02-15', 'Gum graft procedure completed. Good tissue adaptation.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (33, 7, 20, DATE '2024-02-16', 'Multiple surface filling. High-quality composite used.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (34, 4, 36, DATE '2024-02-17', 'Crown preparation revised. New impression taken.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (35, 6, 48, DATE '2024-02-18', 'Complex extraction completed. Socket preservation performed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (36, 2, 44, DATE '2024-02-19', 'Deep scaling under local anesthesia. Significant improvement expected.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (37, 10, 37, DATE '2024-02-20', 'Bridge delivery and cementation. Patient satisfied with result.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (38, 8, NULL, DATE '2024-02-21', 'Custom whitening trays fabricated. Home treatment initiated.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (39, 1, 30, DATE '2024-02-22', 'Recall examination. Oral hygiene has improved significantly.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (40, 9, 46, DATE '2024-02-23', 'Implant crown placement. Excellent esthetic outcome.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (41, 5, NULL, DATE '2024-02-24', 'Midcourse orthodontic evaluation. Treatment progressing as planned.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (42, 3, 39, DATE '2024-02-25', 'Pulpotomy performed. Vital pulp therapy successful.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (43, 7, 43, DATE '2024-02-26', 'Posterior composite restoration. Excellent marginal adaptation.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (44, 2, 47, DATE '2024-02-27', 'Maintenance cleaning performed. Patient compliance excellent.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (45, 12, NULL, DATE '2024-02-28', 'Denture adjustment completed. Improved fit and comfort.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (46, 4, 40, DATE '2024-03-01', 'Gold crown cementation. Premium restoration completed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (47, 1, 45, DATE '2024-03-02', 'Comprehensive examination with X-rays. No pathology detected.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (48, 6, 48, DATE '2024-03-03', 'Wisdom tooth removal. Minimal post-operative swelling.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (49, 11, 31, DATE '2024-03-04', 'Periodontal surgery completed. Flap procedure successful.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (50, 7, 25, DATE '2024-03-05', 'Anterior esthetic filling. Natural appearance achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (51, 9, 17, DATE '2024-03-06', 'Implant second stage surgery. Healing abutment placed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (52, 2, 28, DATE '2024-03-07', 'Subgingival scaling performed. Local anesthesia used.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (53, 5, NULL, DATE '2024-03-08', 'Orthodontic wire change. Progress evaluation positive.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (54, 13, 19, DATE '2024-03-09', 'Veneer preparation completed. Temporary veneers placed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (55, 3, 32, DATE '2024-03-10', 'Apexification procedure initiated. Calcium hydroxide placed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (56, 1, 21, DATE '2024-03-11', 'Routine prophylaxis with oral hygiene instruction.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (57, 8, NULL, DATE '2024-03-12', 'Final whitening session completed. Excellent color match achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (58, 4, 16, DATE '2024-03-13', 'Ceramic crown delivery. Perfect marginal fit confirmed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (59, 7, 33, DATE '2024-03-14', 'Class II composite restoration. Proper contact established.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (60, 10, 24, DATE '2024-03-15', 'Fixed partial denture adjustment. Occlusion refined.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (61, 6, 18, DATE '2024-03-16', 'Simple extraction performed. Socket healing normally.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (62, 2, 41, DATE '2024-03-17', 'Periodontal maintenance. Pocket depths reduced significantly.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (63, 14, NULL, DATE '2024-03-18', 'Night guard delivery. Bruxism protection provided.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (64, 9, 35, DATE '2024-03-19', 'Bone graft placement. Implant site preparation.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (65, 1, 22, DATE '2024-03-20', 'Six-month recall visit. Oral health status excellent.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (66, 3, 14, DATE '2024-03-21', 'Pulp capping procedure. Vital pulp preserved successfully.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (67, 5, NULL, DATE '2024-03-22', 'Retainer delivery. Active orthodontic treatment completed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (68, 7, 27, DATE '2024-03-23', 'Inlay preparation and impression. Indirect restoration planned.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (69, 15, 13, DATE '2024-03-24', 'Tooth mobility treatment. Splinting procedure performed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (70, 4, 36, DATE '2024-03-25', 'Zirconia crown cementation. Superior esthetics achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (71, 2, 44, DATE '2024-03-26', 'Localized antibiotic therapy. Targeted periodontal treatment.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (72, 12, NULL, DATE '2024-03-27', 'Complete denture adjustment. Speaking and chewing improved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (73, 6, 38, DATE '2024-03-28', 'Surgical crown lengthening. Adequate tooth structure exposed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (74, 1, 26, DATE '2024-03-29', 'Emergency examination. Acute pain resolved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (75, 11, 42, DATE '2024-03-30', 'Gingival graft healing evaluation. Excellent tissue integration.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (76, 8, NULL, DATE '2024-03-31', 'Touch-up whitening session. Maintenance of color achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (77, 9, 23, DATE '2024-04-01', 'Abutment connection completed. Ready for crown fabrication.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (78, 3, 15, DATE '2024-04-02', 'Root canal obturation. Three-dimensional seal achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (79, 7, 29, DATE '2024-04-03', 'Occlusal adjustment performed. Bite balanced properly.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (80, 16, 11, DATE '2024-04-04', 'Sealant application completed. Caries prevention measure.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (81, 4, 20, DATE '2024-04-05', 'Temporary crown replacement. New provisional fitted.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (82, 2, 47, DATE '2024-04-06', 'Ultrasonic scaling performed. Calculus removal complete.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (83, 13, 12, DATE '2024-04-07', 'Porcelain veneer bonding. Smile makeover completed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (84, 5, NULL, DATE '2024-04-08', 'Final orthodontic records. Treatment goals achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (85, 1, 34, DATE '2024-04-09', 'Post-treatment evaluation. Patient satisfaction confirmed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (86, 10, 37, DATE '2024-04-10', 'Bridge recementation. Loose restoration repaired.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (87, 6, 48, DATE '2024-04-11', 'Post-extraction follow-up. Healing progressing normally.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (88, 17, NULL, DATE '2024-04-12', 'TMJ evaluation completed. Conservative treatment recommended.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (89, 7, 30, DATE '2024-04-13', 'Preventive resin restoration. Minimal invasive approach.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (90, 9, 46, DATE '2024-04-14', 'Implant maintenance visit. Peri-implant tissues healthy.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (91, 3, 39, DATE '2024-04-15', 'Endodontic treatment completion. Coronal seal placed.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (92, 2, 43, DATE '2024-04-16', 'Periodontal surgery follow-up. Excellent healing response.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (93, 14, NULL, DATE '2024-04-17', 'Sleep apnea appliance adjustment. Improved comfort reported.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (94, 4, 28, DATE '2024-04-18', 'Crown margin refinement. Gingival health improved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (95, 8, NULL, DATE '2024-04-19', 'Professional cleaning with stain removal. Bright smile restored.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (96, 1, 45, DATE '2024-04-20', 'Annual comprehensive exam. Continued good oral health.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (97, 18, 17, DATE '2024-04-21', 'Laser therapy session. Gum inflammation reduced.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (98, 7, 31, DATE '2024-04-22', 'Complex restoration completed. Function fully restored.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (99, 12, NULL, DATE '2024-04-23', 'Denture reline procedure. Improved retention achieved.');
INSERT INTO procedures (plan_id, treatment_id, tooth_id, procedure_date, observations) VALUES (100, 6, 35, DATE '2024-04-24', 'Final suture removal. Surgical site healed completely.');

COMMIT;
