--------------------------------------------------------
-- Archivo creado  - viernes-septiembre-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPOITMENTS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."APPOITMENTS" 
   (	"ID" NUMBER, 
	"PATIENT_ID" NUMBER, 
	"DENTIST_ID" NUMBER, 
	"DATE_TIME" TIMESTAMP (6), 
	"REASON" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("REASON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table DENTAL_HISTORIES
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."DENTAL_HISTORIES" 
   (	"ID" NUMBER, 
	"PATIENT_ID" NUMBER, 
	"ANAMNESIS" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ANAMNESIS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table DENTAL_LABS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."DENTAL_LABS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" CHAR(100 BYTE), 
	"PHONE" CHAR(20 BYTE), 
	"ADDRESS" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("ADDRESS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table DENTISTS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."DENTISTS" 
   (	"ID" NUMBER, 
	"FIRST_NAME" CHAR(100 BYTE), 
	"LAST_NAME" CHAR(100 BYTE), 
	"SPECIALTY" CHAR(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MATERIALS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."MATERIALS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" CHAR(100 BYTE), 
	"DESCRIPTION" CLOB, 
	"STOCK" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table PATIENTS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."PATIENTS" 
   (	"ID" NUMBER, 
	"FIRTS_NAME" CHAR(100 BYTE), 
	"LAST_NAME" CHAR(100 BYTE), 
	"PHONE" CHAR(100 BYTE), 
	"ADDRESS" CHAR(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAYMENTS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."PAYMENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PLAN_ID" NUMBER, 
	"PAYMENT_DATE" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"AMOUNT" NUMBER(10,2), 
	"PAYMENT_METHOD" CHAR(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROCEDURES
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."PROCEDURES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PLAN_ID" NUMBER, 
	"TREATMENT_ID" NUMBER, 
	"TOOTH_ID" NUMBER, 
	"PROCEDURE_DATE" DATE, 
	"OBSERVATIONS" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("OBSERVATIONS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table TEETH
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."TEETH" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"TOOTH_NUMBER" CHAR(10 BYTE), 
	"DESCRIPTION" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table TREATMENT_MATERIALS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" 
   (	"TREATMENT_ID" NUMBER, 
	"MATERIAL_ID" NUMBER, 
	"QUANTITY" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TREATMENT_PLANS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PATIENT_ID" NUMBER, 
	"DENTIST_ID" NUMBER, 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" CHAR(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TREATMENTS
--------------------------------------------------------

  CREATE TABLE "ODONTOLOGY_DEV"."TREATMENTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" CHAR(100 BYTE), 
	"DESCRIPTION" CLOB, 
	"COST" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
REM INSERTING into ODONTOLOGY_DEV.APPOITMENTS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.DENTAL_HISTORIES
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.DENTAL_LABS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.DENTISTS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.MATERIALS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.PATIENTS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.PAYMENTS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.PROCEDURES
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.TEETH
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.TREATMENT_MATERIALS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.TREATMENT_PLANS
SET DEFINE OFF;
REM INSERTING into ODONTOLOGY_DEV.TREATMENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index APPOITMENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODONTOLOGY_DEV"."APPOITMENTS_PK" ON "ODONTOLOGY_DEV"."APPOITMENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DENTAL_HISTORIES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODONTOLOGY_DEV"."DENTAL_HISTORIES_PK" ON "ODONTOLOGY_DEV"."DENTAL_HISTORIES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DENTISTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODONTOLOGY_DEV"."DENTISTS_PK" ON "ODONTOLOGY_DEV"."DENTISTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PATIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ODONTOLOGY_DEV"."PATIENTS_PK" ON "ODONTOLOGY_DEV"."PATIENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DENTISTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."DENTISTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTISTS" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTISTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTISTS" ADD CONSTRAINT "DENTISTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREATMENT_PLANS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" MODIFY ("DENTIST_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PATIENTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."PATIENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PATIENTS" MODIFY ("FIRTS_NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PATIENTS" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PATIENTS" ADD CONSTRAINT "PATIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREATMENTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROCEDURES
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" MODIFY ("TREATMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" MODIFY ("PROCEDURE_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table APPOITMENTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" MODIFY ("DENTIST_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" MODIFY ("DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" ADD CONSTRAINT "APPOITMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DENTAL_HISTORIES
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_HISTORIES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_HISTORIES" MODIFY ("PATIENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_HISTORIES" ADD CONSTRAINT "DENTAL_HISTORIES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TREATMENT_MATERIALS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" MODIFY ("TREATMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" MODIFY ("MATERIAL_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" ADD PRIMARY KEY ("TREATMENT_ID", "MATERIAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."PAYMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PAYMENTS" MODIFY ("PLAN_ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PAYMENTS" MODIFY ("PAYMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PAYMENTS" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."PAYMENTS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DENTAL_LABS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_LABS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_LABS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_LABS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TEETH
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."TEETH" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TEETH" MODIFY ("TOOTH_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."TEETH" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MATERIALS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."MATERIALS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."MATERIALS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ODONTOLOGY_DEV"."MATERIALS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table APPOITMENTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" ADD CONSTRAINT "APPOITMENTS_FK1" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "ODONTOLOGY_DEV"."PATIENTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ODONTOLOGY_DEV"."APPOITMENTS" ADD CONSTRAINT "APPOITMENTS_FK2" FOREIGN KEY ("DENTIST_ID")
	  REFERENCES "ODONTOLOGY_DEV"."DENTISTS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DENTAL_HISTORIES
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."DENTAL_HISTORIES" ADD CONSTRAINT "DENTAL_HISTORIES_FK1" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "ODONTOLOGY_DEV"."PATIENTS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENTS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."PAYMENTS" ADD CONSTRAINT "FK_PAYMENT_PLAN" FOREIGN KEY ("PLAN_ID")
	  REFERENCES "ODONTOLOGY_DEV"."TREATMENT_PLANS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROCEDURES
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" ADD CONSTRAINT "FK_PROCEDURE_PLAN" FOREIGN KEY ("PLAN_ID")
	  REFERENCES "ODONTOLOGY_DEV"."TREATMENT_PLANS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" ADD CONSTRAINT "FK_PROCEDURE_TOOTH" FOREIGN KEY ("TOOTH_ID")
	  REFERENCES "ODONTOLOGY_DEV"."TEETH" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ODONTOLOGY_DEV"."PROCEDURES" ADD CONSTRAINT "FK_PROCEDURE_TREATMENT" FOREIGN KEY ("TREATMENT_ID")
	  REFERENCES "ODONTOLOGY_DEV"."TREATMENTS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TREATMENT_MATERIALS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" ADD CONSTRAINT "FK_TM_MATERIAL" FOREIGN KEY ("MATERIAL_ID")
	  REFERENCES "ODONTOLOGY_DEV"."MATERIALS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_MATERIALS" ADD CONSTRAINT "FK_TM_TREATMENT" FOREIGN KEY ("TREATMENT_ID")
	  REFERENCES "ODONTOLOGY_DEV"."TREATMENTS" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TREATMENT_PLANS
--------------------------------------------------------

  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" ADD CONSTRAINT "FK_PLAN_DENTIST" FOREIGN KEY ("DENTIST_ID")
	  REFERENCES "ODONTOLOGY_DEV"."DENTISTS" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "ODONTOLOGY_DEV"."TREATMENT_PLANS" ADD CONSTRAINT "FK_PLAN_PATIENT" FOREIGN KEY ("PATIENT_ID")
	  REFERENCES "ODONTOLOGY_DEV"."PATIENTS" ("ID") ON DELETE CASCADE ENABLE;
